# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Node.js Package

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: npm ci

  publish-npm:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/
      - run: npm ci
      - run: git config --global user.email "szunyogh.tamas@gmail.com"
      - run: git config --global user.name "Tamas Szunyogh"
      - run: npm version $(git describe --tags --abbrev=0) --force
      - run: cd projects/ngx-number-mask && npm version $(git describe --tags --abbrev=0) --force
      - run: git push --follow-tags
      - run: npm run build
      - run: npm publish dist/ngx-number-mask/
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
